title: 'The 2023 Thomas J. Watson Fellows'
description: 'Watson Fellows prusue a rare window of time after college to engage their deepest interests on a world scale.'
img: '/images/social-card.jpg'

sass:
  style: compressed
  load_paths:
    - _sass

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - bin
  - vendor

collections:
  fellows:
    output: true
    sort_by: title

plugins:
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      image: /images/social-card.png